### ISSUE TITLE
As Product Owner, I want residents to be able to independently obtain their own housing history as registered in BRP  ...

### ISSUE THREAD

**Issue by sgort** [discipl/waardepapieren#123]
... in such a way that they can offer this as verifiable evidence to the relevant home owners, without the need for human support from the municipality.

**Acceptance criteria**
- [ ] Credential definitions are clear
- [ ] Issuer information is known
- [ ] Applicable GDPR compliancy is modelled via FLINT
- [ ] The provision of Waardepapieren with the credentials is derived from and in accordance with the aforementioned FLINT model

**Definition of ready**
- [ ] Acceptance criteria have been formulated
- [ ] Everyone on the team understands the story
- [ ] Desired functionality is clear and described
- [ ] The method of demonstration should be clear
- [ ] User story has been analyzed (with architecture, data model and technical decisions)
- [ ] Recorded in GitHub and moved to Ready column

**Definition of done**
- [ ] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [ ] Story has been automatically tested
- [ ] Story can be demonstrated using code on master branch
- [ ] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by sgort** [comment]
@robertvandoesburg help even mee nadenken / afbakenen relevantie en/of geschiktheid FINT in dit specifieke geval.

**Comment by pimotte** [comment]
@sgort 

TODO to include this functionality in the current implementation:

- [ ] Extend [mock API](https://github.com/discipl/waardepapieren/blob/master/mock-nlx/index.js) with endpoint and request/response pair to provide residence history
- [ ] Extend [docker-compose file](https://github.com/discipl/waardepapieren/blob/master/docker-compose-travis.yml#L3) with a second instance of waardepapieren with a separate configuration https://github.com/discipl/waardepapieren/blob/master/waardepapieren-service/configuration/waardepapieren-config-compose-travis.json#L11 (might need to have a seperate certificate as well). Do make sure that the second waardepapieren instance connects to the ephemeral server of the first!
- [ ] Optional: Change the [config of clerk-frontend](https://github.com/discipl/waardepapieren/blob/master/clerk-frontend/src/configuration/clerk-frontend-config.json) to check if the residence history can be retrieved.
- [ ] Change ["PRODUCT_*" properties in config of clerk-frontend](https://github.com/discipl/waardepapieren/blob/master/clerk-frontend/src/configuration/clerk-frontend-config.json#L7) to be arrays and use those arrays in the frontend.


The last point is the only one where actual coding is needed. The second point can also be accomplished by changing the waardepapieren-service to produce multiple different waaardepapieren, but this was the original architecture, and I think it makes sense to keep it.

**Comment by sgort** [comment]
@pimotte I've trouble understandig the "identificatie": "da02a3ac-4412-11e9-b210-d663bd873d93", in mock API...

**Comment by pimotte** [comment]
So this API is actually something we "borrowed" from a mock API that was running on NLX, but at some point it disappeared. To us, this "identificatie" attribute doesn't serve any function, as the waardepapieren service selects part of the response as attribute (see that config).

The app.get function basically maps a path to a response, you can simply copy it, change the path, and change the response. If you're looking for some mock data for your use case, perhaps [the lost lemon API](https://haalcentraal.lostlemon.nl/openapi/index.html) can inspire?

**Comment by sgort** [comment]
Hoi Pim, hoe loop ik door deze JSON Array https://github.com/discipl/waardepapieren/blob/6a50c6549947f883d47033dba1f4a784920a40c1/mock-nlx/index.js#L171 heen als ik de adressen onder elkaar wil printen op het Waardepapier https://github.com/discipl/waardepapieren/blob/6a50c6549947f883d47033dba1f4a784920a40c1/waardepapieren-verblijfplaatshistorie-service/configuration/waardepapieren-verblijfplaatshistorie-config-compose-travis.json#L28 ?

**Comment by pimotte** [comment]
Ik zou voor nu even kijken wat er gebeurt als je "TestArrayAdressen" doet.

De rechterhelft is een json-path expressie, maar we tonen vervolgens alleen de eerste match, dus dat zou problematisch kunnen worden als je meerdere dingen wil tonen. Ik vermoed ook dat je de keys van de addressen een meer mensvriendelijke naam wil geven. Ik weet niet of de huidige oplossing hier genoeg voor is.

Als bovenstaande oplossing niet werkt, kan je dan specificeren wat je zou willen en dan kijken we aan het einde hoe we dat voor elkaar krijgen?

**Comment by sgort** [comment]
Cool. TestArrayAdressen haalt de hele array op (zie verblijfplaatshistorie).

![image](https://user-images.githubusercontent.com/25812095/76950826-ef15e380-690a-11ea-8622-36f3fde26728.png)

Wat dan nog rest is de vraag om ze op de pdf geprint te krijgen...
[uittreksel.pdf](https://github.com/discipl/waardepapieren/files/4348400/uittreksel.pdf)

**Comment by sgort** [comment]
Ik ga nu hiermee puzzelen. ;-)

- [ ] Change "PRODUCT_*" properties in config of clerk-frontend to be arrays and use those arrays in the frontend.

**Comment by sgort** [comment]
Hoppa. Ik ben er bijna! PRODUCT_* properties array is config en gebruik in front end. Blijf ik met de allerlaatste puzzel zitten. Hoe maak ik kiezen tussen 0 en 1 mogelijk? https://github.com/discipl/waardepapieren/blob/9285d2c68c76b02ea4c54b2a0ec79c7a0c0644a9/clerk-frontend/src/need-wizard/ConfirmStep.js#L24

**Comment by sgort** [comment]
En om de draad nav mijn fout gisteren (Dank voor de fix!) met het logo van Hoorn weer op te pakken: hoe regel ik het logo voor de Hoorn variant?

**Comment by pimotte** [comment]
Kiezen, volgens mij zou dat moeten werken als je in de regel die je noemt `CONFIGURATION.PRODUCTS[0].PRODUCT_NEED` vervangt met `this.props.need`

**Comment by pimotte** [comment]
Voor Hoorn logo, voeg het logo toe in de `./clerk-frontend/public/form-assets/` map en verander het pad in `/clerk-frontend/src/configuration/clerk-frontend-config.json` (specifiek de logoImage property).

(Bij voorkeur in een andere branch dan waar je voor hier bezig bent, denk ik? ;))

**Comment by sgort** [comment]
Nagenoeg klaar. Heb array toegevoegd aan NeedStep https://github.com/discipl/waardepapieren/blob/2c5dca0b19a3f64e472e369d0cf2d23e60f91ad4/clerk-frontend/src/need-wizard/NeedStep.js#L6 en die toont netjes in de dropdown beide PRODUCTS maar de this.prop.need die in ConfirmStep heb gezet levert in beide gevallen steeds hetzelfde PRODUCT, nl de eerste...

**Comment by pimotte** [comment]
Ik kan vrij lastig uit de code zien wat het probleem hier is. Ik zou even goed naar de logs kijken, beginnend bij de docker-compose logs en daarna de browser console.

**Comment by sgort** [comment]
Man man. Wat jij in 3 uur kan, daar zit ik 3 dagen op te zweten... Haha. Maar goed. Hartstikke leerzaam en motiveert enorm!!

En ja, ik heb de boosdoener gevonden. Deze hard coded NEED[0] veroorzaakt het niet functioneren van de selectie (eronder vermoed ik?) https://github.com/discipl/waardepapieren/blob/11ba17c56e2863024e695c3984a05387e647b5d6/clerk-frontend/src/need-wizard/NeedStep.js#L21

**Comment by pimotte** [comment]
Oeh, ja, dat zal hem wel zijn

**Comment by sgort** [comment]
Ok. Ik gooi de handdoek in de ring. Ik zit eindeloos te puzzelen en met voorbeeld code te stoeien. Krijg het niet voor elkaar om de dropdown selectie van NeedStep.js aan boord te hengelen van this.props.needChanged. Ik moet m'n verlies en onkunde hier onder ogen zien. Is niet anders.

Wil jij hier naar kijken?

Ik ga nog een poging doen om het renderen van de verblijfplaatshistorie op de pdf te fixen. Maar nu eerst nog even Netflixen :-D

**Comment by sgort** [comment]
Ok. Wat mij betreft is de code klaar. Op issue hiervoor na.

Ik heb inmiddels ontdekt dat ik voor de aanpassing op de pdf (de TestArrayAdressen toont daar als [object Object], [object Object], etc..) bij de paper wallet repo moet zijn. Ik maak daarvoor een issue aan met - ook weer - een aparte branch om daarmee te puzzelen. Ok?

**Comment by pimotte** [comment]
TODO voor merge:

- [ ] Changes van afgelopen week meenemen @sgort gaat dit opnieuw toepassen vanaf master voor de oefening naar nieuwe branch
- waardepapieren-service dedupliceren:
  - [ ] Zorgen dat het wel/niet draaien van de EphemeralServer in waardepapieren-service configurabel is
  - [ ] Herschrijven docker-compose waardepapieren-verblijfplaatshistorie-service naar image van waardepapieren-service met andere config
  - [ ] Verwijderen codebase waardepapieren-verblijfplaatshistorie-service


Out of scope voor deze issue: Toepassing van Hoorn-logo op waardepapier

**Comment by sgort** [comment]
Nice. Ik moet nog even stoeien met de build dir van de verblijfplaatshistorie-service, want daar gaat iets nog niet goed, maar ik ben al goed onderweg.

### vraag
Ik heb het wel/niet draaien van Ephemeral op een nogal 'slechte' manier gedaan vind ik, maar ik weet even niet beter. Zie https://github.com/discipl/waardepapieren/blob/1b5a2c720093ef057205880ce603732fc10debee/waardepapieren-service/src/waardepapieren-service.js#L23
Dat kan vast beter. Maar hoe?

**Comment by pimotte** [comment]
Sowieso is de else clause overbodig.

Ik zou gewoon een nieuwe configuratie optie introduceren, en die toevoegen
aan beide configs

**Comment by sgort** [comment]
Pim, waar is de /clerk-frontend/src/configuration/clerk-frontend-config.json gebleven? Die is weg na de merge vandaag in de master. Nu weet ik niet waar ik de PRODUCT_* properties array moet laten, of hoe dat anders op te lossen.
Ben terug bij waar ik eerder vast raakte: de propagation of needs in de need-wizard.

**Comment by pimotte** [comment]
Die staat in de public map, omdat ie nu runtime opgehaald wordt.

Voor die propagation kan je kijken of het lukt op basis van mijn commit op
jouw branch, als het niet lukt doe ik die wel weer:)

**Comment by sgort** [comment]
PR aangemaakt.

**Comment by sgort** [comment]
Nog een nabrander. Ik wil gaan puzzelen met dit [issue bij discipl-paper-wallet](https://github.com/discipl/discipl-paper-wallet/issues/18), hoe zorg ik er nu voor dat ik mijn pogingen kan testen in de (inmiddels afgeronde) branch issue123-refactoring op mijn eigen computer? Het gaat dan om deze import. Hoe vervang ik die (tijdelijk) met de fix die ik lokaal in de aparte paper-wallet branch uitprobeer?
https://github.com/discipl/waardepapieren/blob/d32d41282db36a18c8cb02f4a887c558d41221d5/clerk-frontend/src/need-wizard/DeliveryStep.js#L3
