### ISSUE TITLE
As a municipality clerk I want to enter someones BSN ...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#2]
... such that the process of obtaining their "Uittreksel BRP" can be started.

**Acceptance criteria**
- [x] Minimal web-interface with field for BSN and 'next' button
- [x] No authentication
- [x] Clerk frontend project is created, minimal react app, no docker, npm start is enough
- [x] No tests needed

**Definition of ready**
- [x] Acceptance criteria have been formulated
- [x] Everyone on the team understands the story
- [x] Desired functionality is clear and described
- [x] Is small enough (at most 1/3 of sprint)
- [x] The method of demonstration should be clear
- [x] User story has been analyzed (with architecture, data model and technical decisions)
- [x] Recorded in GitHub and moved to Ready column

**Definition of done**
- [x] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [x] ~~Story has been automatically tested~~
- [ ] Story can be demonstrated using code on master branch
- [x] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by bkaptijn** [comment]
includes calling an initial implementation of discipl-core-restapi (conforming to OAS 3) though a local usage of the discipl-abundance-service component

**Comment by pimotte** [comment]
> includes calling an initial implementation of discipl-core-restapi (conforming to OAS 3) though a local usage of the discipl-abundance-service component

This has been included in #4 instead
