### ISSUE TITLE
As a potential new developer I want a documented build process ...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#3]
... such that I can get up to speed easily.

**Acceptance criteria**
- [ ] Build process is documented in CONTRIBUTING.md

**Definition of ready**
- [ ] Acceptance criteria have been formulated
- [ ] Everyone on the team understands the story
- [ ] Desired functionality is clear and described
- [ ] Is small enough (at most 1/3 of sprint)
- [ ] The method of demonstration should be clear
- [ ] User story has been analyzed (with architecture, data model and technical decisions)
- [ ] Recorded in GitHub and moved to Ready column

**Definition of done**
- [ ] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [ ] Story has been automatically tested
- [ ] Story can be demonstrated using code on master branch
- [ ] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by sgort** [comment]
Close it to clean up. Will re-open / create a new issue where applicable.
