### ISSUE TITLE
As municipality I want a smaller QR code ...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#37]
... such that a citizen will be less intimidated by it.

**Acceptance criteria**
- [ ] Research if and how it is possible to decrease the size of QR code

**Definition of ready**
- [ ] Acceptance criteria have been formulated
- [ ] Everyone on the team understands the story
- [ ] Desired functionality is clear and described
- [ ] Is small enough (at most 1/3 of sprint)
- [ ] The method of demonstration should be clear
- [ ] User story has been analyzed (with architecture, data model and technical decisions)
- [ ] Recorded in GitHub and moved to Ready column

**Definition of done**
- [ ] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [ ] Story has been automatically tested
- [ ] Story can be demonstrated using code on master branch
- [ ] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by pimotte** [comment]
Possible avenues that I see working out here, roughly sorted in the order in which I would probably try them. 

- Not generate nonces, but have stable identifiers. Evaluate impact on functionality and security.
- More efficient serialization format than json (protobuf?)
- Deduplicate public-key data in dids/links (impacts architecture)
- Just use hash and save actual claim on some content-addressable decentralized platform (needs encryption)
- Reduce key sizes (implacts security)
- Move from attestation and claim to just claim (impacts architecture)

**Comment by bkaptijn** [comment]
we discussed to change the behavior of ephemeral storage:
- no nonces in claim id in links => you can not have similair claims multiple times in a channel, signatures are the claim id in links
- remove public key from claim id in links as they can be looked up or are given => little performance penalty
This may make a link 250 chars shorter and thus saves 500 chars in the QR

another improvement may be that the paper wallet implementation could be allowed to be fixed to a certain platform (connector); it could then omit the did and link prefixes in the QR, adding them at scan as they are for instance fixed to (did|link):discipl:ephemeral, saving another 86 chars.

**Comment by bkaptijn** [comment]
try to improve QR size even further in sprint 4 by only exporting and importing the claim if it was already claimed by the attestor did. The product name in the attestation should also be included in the claim it self then though.
