### ISSUE TITLE
As municipality I want the data in a waardepapier to be representative ...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#38]
... such that it looks like an actual waardepapier.

@BoerBas will provide samples of api call (HTTP method, parameters, headers), result (SOAP, wsdl if possible) and sample waardepapier-data (what the user should see) for this result.

**Acceptance criteria**
- [ ] ~~Retrieve data from Haarlem test NLX server~~
- [x] Improve mock data
- [x] Show data in clear way

**Definition of ready**
- [x] Acceptance criteria have been formulated
- [x] Everyone on the team understands the story
- [x] Desired functionality is clear and described
- [x] Is small enough (at most 1/3 of sprint)
- [x] The method of demonstration should be clear
- [x] User story has been analyzed (with architecture, data model and technical decisions)
- [x] Recorded in GitHub and moved to Ready column

**Definition of done**
- [x] Story satisfies acceptance criteria
- [x] Implementation of story has been code reviewed
- [x] Story has been automatically tested
- [x] Story can be demonstrated using code on master branch
- [x] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by pimotte** [comment]
After investigation it turned out that the SOAP service is not publicly available through NLX, so we decided to improve the mock data for now.

**Comment by bkaptijn** [comment]
After meeting Bart Jeukendrup at VNG common ground, they helped in providing a mock service through NLX with filtering capabillities. Adjusted code and docker compose to use this service instead. (a PR at the moment)

**Comment by bkaptijn** [comment]
We still need support for nested (json) data. (back to in sprint 4)
