### ISSUE TITLE
As municipality clerk I want express a need for an Uittreksel BRP on behalf of a citizen ...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#4]
... such that this need can be fulfilled.

In this phase the only need is "Uittreksel BRP"

**Acceptance criteria**
- [ ] Clerk can select need in web-interface (created in #2)
- [ ] Data that will be requested it shown (NAW)
- [ ] At client side, discipl-abundance-service is used to express the need with the BSN as additional information on a discipl-core-ephemeral connector on the local discipl node through the discipl-core-jsonrpc-service

**Definition of ready**
- [ ] Acceptance criteria have been formulated
- [ ] Everyone on the team understands the story
- [ ] Desired functionality is clear and described
- [ ] Is small enough (at most 1/3 of sprint)
- [ ] The method of demonstration should be clear
- [ ] User story has been analyzed (with architecture, data model and technical decisions)
- [ ] Recorded in GitHub and moved to Ready column

**Definition of done**
- [ ] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [ ] Story has been automatically tested
- [ ] Story can be demonstrated using code on master branch
- [ ] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by sgort** [comment]
Close it to clean up. Will re-open / create a new issue where applicable.
