### ISSUE TITLE
Bug : the NLX outway sometimes initially gives a 500 internal server error response

### ISSUE THREAD

**Issue by bkaptijn** [discipl/waardepapieren#51]
It seems that sometimes the NLX outway gives a HTTP 500 internal server error response. When you reload the expected result is shown though.

**Comment by bkaptijn** [comment]
after docker-compose up and filling out the forms with a new bsn not previously used I get no result and the following in the logs:

> waardenpapieren-service@0.2.0 start /app
> node --require @babel/register src/index.js

Ephemeral server listening on 3232!
(node:18) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bkaptijn** [comment]
note that when clicking previous and next again it suddenly works...

**Comment by sgort** [comment]
Close it to clean up. Will re-open / create a new issue where applicable.
