### ISSUE TITLE
Deployment to test environment

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#88]
TODO:
- Bas: Give access to Steven
- Steven: Deploy to test environment and communicate missing information in documentation.

**Comment by sgort** [comment]
@boscp08 zoals besproken. Ter lering ende vermaeck gaarne de Waardepapieren deployment naar je eigen test (laptop) doen met als doel:
- inzicht verkrijgen software stack Waardepapier (irt visie Discipl et al)
- completeren documentatie waar nodig/nuttig naar eigen inzicht.

**Comment by sgort** [comment]
[Blok 4_ implementatie en techniek.pptx.pdf](https://github.com/discipl/waardepapieren/files/3626464/Blok.4_.implementatie.en.techniek.pptx.pdf)

**Comment by boscp08** [comment]
https://github.com/discipl/waardepapieren  issue#88
https://zuidugchelen.eu/ BSN=663678651 clerk-frontend serving needs   cookbook (disclaimer under construction)  https://github.com/boscp08/waardepapieren/wiki/Mac-Mini--macOS-Sierra-10.16 )

**Comment by boscp08** [comment]
vi config 
ssh root@86.86.102.241   F0B...ZE
ssh boscp08@192.168.2.19

boscp08s-mini:validator-frontend boscp08$ pwd
Users/boscp08/Projects/scratch/virtual-insanity/waardepapieren/

https://www.google.nl/maps/place/Brouwersmolenweg,+Ugchelen/@52.1821233,5.9245121,19.16z/data=!4m5!3m4!1s0x47c7b838a5d9dfad:0xddb1851b6a1e78ee!8m2!3d52.1853196!4d5.9276967

**Comment by boscp08** [comment]
https://github.com/boscp08/waardepapieren/wiki/linuxmint-19.2-cinnamon-32bit--linux-i386  een eerste probeersel. 
$ docker --version Docker version 18.09.7, build 2d0083d boscp08@cinnemon:~
$ docker-compose --version docker-compose version 1.17.1, build unknown

errors...
boscp08@cinnemon:~/Projects/scratch/virtual-insanity/waardepapieren$ `sudo docker-compose -f docker-compose-travis.yml up`

Creating network "waardepapieren_default" with the default driver Building mock-nlx Step 1/6 : FROM node:10 10: Pulling from library/node **ERROR: Service 'mock-nlx' failed to build: no matching manifest for linux/386 in the manifest list entries**
